### ISSUE TITLE
esp32-s2 Support

### ISSUE THREAD

**Issue by hakasapl** [beegee-tokyo/SX126x-Mesh-Network#1]
Hi,

We have a ESP32-S2 board. Specifically, the esp32 s2 saola 1: https://www.adafruit.com/product/4693

Here's how we modified your platformio.ini...

```
[env:esp32s2]
platform = https://github.com/platformio/platform-espressif32.git#feature/arduino-idf-master
board = esp32-s2-saola-1
framework = arduino
upload_port = COM4
upload_speed = 921600
board_build.f_cpu = 160000000L
build_flags = 
	-DBOARD_HAS_PSRAM=TRUE
	-mfix-esp32-psram-cache-issue
	-DHAS_DISPLAY=0
	-DSW_VERSION=1.0
	-DMYLOG_LOG_LEVEL=MYLOG_LOG_LEVEL_ERROR
	-DOLED_SDA=13
	-DOLED_SCL=32
	-DIS_WROVER=1
lib_deps = 
	SX126x-Arduino
```

But when I build I get this error:

```
src/BLE/ble_esp32.cpp:9:10: fatal error: esp_bt_device.h: No such file or directory
```

When I delete BLE related elements of the program, it looks like it compiles fine, but then results in a linker error at the last second.

Is the s2 supported at all? Thanks for your time!

**Comment by beegee-tokyo** [comment]
I do not have an ESP32-S2, so I cannot test.

Regarding the BLE include error, I didn't touch the software for a long time. If I remember correct I used NimBLE library and you might need to add it in the lib_deps in platformio.ini => `h2zero/NimBLE-Arduino`

**Comment by hakasapl** [comment]
I gave that a shot but `esp_bt_device.h` is still not found. Thanks for checking. I thought that header came from the espidf framework, so I loaded that in addition to `arduino` in platform.ini but that results in a cmake error and that esp32-s2 cannot be found in the toolchain when building.

I'll keep digging, thanks for your quick reply!
